### ISSUE TITLE
Bug - Menu message erreur, plus data non rafraichit.

### ISSUE THREAD

**Issue by Y-Picot** [BoisselNicolas/RESOURCES-RELATIONNELLES#10]
## Contexte

Un problème qui demande de rafraichir la page pour mettre à jour la donnée.
Menu affichant un message d'erreur lorsque l'on rappelle après connexion puis déconnexion

## Objectifs

- [x] Menu affichant un message d'erreur 
- [x] Rafraichissement de la donnée effective après F5

**Comment by BoisselNicolas** [comment]
Bug menu fix : commit bd959971036e754463f8273a9e3d65ce967dbabe
