### ISSUE TITLE
Veille - Faille des technologies utiliser

### ISSUE THREAD

**Issue by Y-Picot** [BoisselNicolas/RESOURCES-RELATIONNELLES#13]
Le sujet du ticket d'établir une liste de document relatant les problèmes potentiel : 
    - panne de service
    - action malveillante pouvant modifier les données
    - abus du système mise en place pour en tirer un statu spécifiques
    - etc...

Pour effectuer la tâche, il faut mettre ça recherche sur le gdrive de la veille avec : la technologie plus un lien et une explication.
Lors de la réunion du jeudi, nous pourrons ensuite acculturer le groupe à ses problèmes et réfléchir aux actions que nous pourrions mener ou non celons la gravité de la tâche. Essayer de mesurer son impact avec les outils présenter pendant la semaine sécu.

Afin de pouvoir trouver des informations une méthode :
Google : CVE Détails NomTechnologies

https://drive.google.com/drive/folders/1Pu_zHDfeENi5217cb5SNG759QNDFZT1i

Applicatifs :
   - Ionic
   - Express
   - Vue.js
 
Server : 
  - SubSystem Ubuntu
  - Ubuntu
  - Windows shell
 

Librairies :
 - cors
 -  express
- body-parser
- mongoose
- jsonwebtoken
- md5

Ce ticket est en construction et peut-être modifier par tous le monde si il manque quoi que ce soit.

**Comment by YTBeater** [comment]
https://drive.google.com/drive/folders/1Pu_zHDfeENi5217cb5SNG759QNDFZT1i
