### ISSUE TITLE
API - Restructuration du serveur express

### ISSUE THREAD

**Issue by Y-Picot** [BoisselNicolas/RESOURCES-RELATIONNELLES#7]
## Objectifs

- [x] 1 fichier par table 
- [x]  fichier de fonction model par table
- [x]  la fonction 'vérification de tokens 

  ![image](https://user-images.githubusercontent.com/49924352/110817627-c52c9e00-828c-11eb-94f9-a78bd990862a.png)

**Comment by Y-Picot** [comment]
Branch assigné au ticket : e918296

**Comment by yoan22** [comment]
test

**Comment by yoan22** [comment]
@YTBeater yo

**Comment by yoan22** [comment]
sidn

**Comment by Y-Picot** [comment]
78753d2

**Comment by Y-Picot** [comment]
789e0c0

**Comment by Y-Picot** [comment]
Je suis en train de rebase pour voir si les patchs fait par Nicolas B passe bien avec mon code. je place le code en à tester sur Dev en attendant plus de résultat considérant la partie ticket effectué à 100 % et la branche master comme un problème hors ticket.
